#!/bin/bash

# kmbrlynn April 2015
# Run the main App Inventor server
# find current AppEngine Java SDK at: http://cloud.google.com/appengine/downloads

ai=/home/kmbrlynn/Repos/appinventor-sources/appinventor
javasdk=/opt/appengine-java-sdk-1.9.19

$javasdk/bin/dev_appserver.sh --port=8888 --address=0.0.0.0 $ai/appengine/build/war/
